version: '3.8'

services:
  postgres:
    image: postgres:18  # Use PostgreSQL 18 image
    container_name: postgres
    environment:
      POSTGRES_DB: order  # Name of the database
      POSTGRES_USER: docker  # PostgreSQL user
      POSTGRES_PASSWORD: docker  # PostgreSQL password
      POSTGRES_TCP_PORT: 5432  # Port for PostgreSQL
    ports:
      - "5432:5432"  # Expose port 5432 for PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume to persist PostgreSQL data
    networks:
      - shared_network  # Shared network with Orderservice

  orderservice:
    build:
      context: .  # Current directory (where Dockerfile is located)
      dockerfile: Dockerfile  # Points to Dockerfile for building the image
    container_name: orderservice
    depends_on:
      - postgres  # Ensure PostgreSQL starts before Orderservice
    ports:
      - "3000:3000"  # Expose port 3000 for Orderservice
    environment:
      DB_HOST: postgres  # Hostname of the PostgreSQL container
    command: ["./ordersystem"]  # Command to start the Orderservice binary
    networks:
      - shared_network  # Shared network with PostgreSQL

networks:
  shared_network:
    driver: bridge  # Use default 'bridge' network driver

volumes:
  postgres_data:  # Volume to persist PostgreSQL data
